### ISSUE TITLE
Is the Training Data Available?

### ISSUE THREAD

**Issue by tokestermw** [piotrmirowski/DependencyTreeRnn#1]
Hi, thanks for the great project.

I was wondering if the preprocessed training data was available?

**Comment by andreasvlachos** [comment]
Greetings,

Here it is: https://drive.google.com/file/d/0BwPdBcatuO0vS3JlUVBtZHpSb3M/view?usp=sharing

Note that the preprocessed validation and testing data is also there. I am updating the README with the link.
