### ISSUE TITLE
Speed Issues

### ISSUE THREAD

**Issue by tokestermw** [piotrmirowski/DependencyTreeRnn#3]
Hi, 

I am experiencing almost 1000x(!) slower training (and testing) speed compared to similar RNN code.

Mikolov RNNLM (http://rnnlm.org) gets 49K words per second on the PTB dataset.

The Yandex faster RNNLM version is also fast (https://github.com/yandex/faster-rnnlm), somewhere in the range of processing tens of thousands of words per second.

With DependencyTreeRnn, I am getting 50 ~ 80 words per second. 

I wonder where the speed bottleneck is? I would expect dependency version to be a little slower but not this stark of a difference :)

**Comment by piotrmirowski** [comment]
Hello tokestermw,
I am sorry for the speed issues. This actually surprises me quite a lot. I just tested running the code on a MacBook Air (1.7 GHz Intel Core i7, 8GB RAM) after compiling my code in XCode. I obtained about 6K to 8K words per second on PTB - definitely not 50 to 80. Running this code on my MacBook Pro or on a Linux server achieved even faster performance. Would you like to chat about this problem?

**Comment by tokestermw** [comment]
It looks like the hidden layer size affects the speed greatly.

For 600 nodes it goes around 80 words / sec. For 200 nodes it goes 1300 words per sec. For 100 nodes it goes 4000 words / sec.

This is on my 2009 Macbook Pro using OpenBlas 0.2.18.

Probably a matter of optimization.

Thanks.
